import { DEFAULT_CONTAINER_STYLE, DEFAULT_ITEMS } from "./initial-states";

export const PRESETS = [
  {
    name: "Flex defaults",
    flexContainerStyle: DEFAULT_CONTAINER_STYLE,
    flexItems: DEFAULT_ITEMS,
  },
  {
    name: "Even columns",
    flexContainerStyle: { width: "60%", minWidth: "auto", maxWidth: "auto", height: "auto", minHeight: "auto", maxHeight: "auto", display: "flex", flexDirection: "row", flexWrap: "nowrap", justifyContent: "start", alignItems: "stretch", alignContent: "stretch", rowGap: "4px", columnGap: "4px" },
    flexItems: [
      {
        id: "qSUmVL",
        content: "Short",
        style: {
          width: "auto",
          maxWidth: "auto",
          minWidth: "auto",
          height: "auto",
          maxHeight: "auto",
          minHeight: "auto",
          flex: "1 1 0",
          alignSelf: "auto",
          order: "0",
          marginTop: "0",
          marginRight: "0",
          marginBottom: "0",
          marginLeft: "0",
        },
      },
      {
        id: "2gvvpf",
        content: "Medium length content",
        style: {
          width: "auto",
          maxWidth: "auto",
          minWidth: "auto",
          height: "auto",
          maxHeight: "auto",
          minHeight: "auto",
          flex: "1 1 0",
          alignSelf: "auto",
          order: "0",
          marginTop: "0",
          marginRight: "0",
          marginBottom: "0",
          marginLeft: "0",
        },
      },
      {
        id: "3obMB8",
        content: "Very long text content. Applying flex: 1 to every flex item makes even columns regardless of their size.",
        style: {
          width: "auto",
          maxWidth: "auto",
          minWidth: "auto",
          height: "auto",
          maxHeight: "auto",
          minHeight: "auto",
          flex: "1 1 0",
          alignSelf: "auto",
          order: "0",
          marginTop: "0",
          marginRight: "0",
          marginBottom: "0",
          marginLeft: "0",
        },
      },
      {
        id: "nmPqzI",
        content: "",
        style: {
          width: "auto",
          maxWidth: "auto",
          minWidth: "auto",
          height: "auto",
          maxHeight: "auto",
          minHeight: "auto",
          flex: "1 1 0",
          alignSelf: "auto",
          order: "0",
          marginTop: "0",
          marginRight: "0",
          marginBottom: "0",
          marginLeft: "0",
        },
      },
    ],
  },
  {
    name: "flex-grow 9999 Hack",
    flexContainerStyle: { width: "auto", minWidth: "auto", maxWidth: "auto", height: "auto", minHeight: "auto", maxHeight: "auto", display: "flex", flexDirection: "row", flexWrap: "wrap", justifyContent: "start", alignItems: "stretch", alignContent: "stretch", rowGap: "4px", columnGap: "4px" },
    flexItems: [
      {
        id: "qSUmVL",
        content: "Short",
        style: {
          width: "auto",
          maxWidth: "auto",
          minWidth: "auto",
          height: "auto",
          maxHeight: "auto",
          minHeight: "auto",
          flex: "1 1 auto",
          alignSelf: "auto",
          order: "0",
          marginTop: "0",
          marginRight: "0",
          marginBottom: "0",
          marginLeft: "0",
        },
      },
      {
        id: "2gvvpf",
        content: "Long content. Resize the window and watch how both items stack on top of each other. Example adapted from https://www.joren.co/flex-grow-9999-hack/",
        style: {
          width: "40rem",
          maxWidth: "auto",
          minWidth: "auto",
          height: "auto",
          maxHeight: "auto",
          minHeight: "auto",
          flex: "9999 1 auto",
          alignSelf: "auto",
          order: "0",
          marginTop: "0",
          marginRight: "0",
          marginBottom: "0",
          marginLeft: "0",
        },
      },
    ],
  },
];
